### PR TITLE
fix: Bug where header menu did not appear after switching

### PR DESCRIPTION
**Pull request by pbullhove**
## What does this pull request change?

Fixes bug where one can not select application again after switching. 
Did this by changing from eds.Menu to eds.Popover. 

Looks a bit different now as well. 

image

## Issues related to this change
#771

### CODE REVIEW

**Comment by henrikbossart** [comment]
I whipped up slight tweak to your popover, just some style changes. have a look :+1:

#777

**Comment by pbullhove** [comment]
> I whipped up slight tweak to your popover, just some style changes. have a look 👍
> 
> #777
> 
> Screenshot 2023-11-21 at 21 00 53
> 😄

**Comment by pbullhove** [comment]
Perhaps should we make the highlight color the same as rest of plugins do? More the light green and gray for consistency? 

And would a border around the popover be nice in order to separate it from the rest of the content? 



image

**Comment by henrikbossart** [comment]
@pbullhove actually, we should probably wrap the button text in a `<Typography>` tag, which will give it the same style as other texts used in the app.

**Comment by pbullhove** [comment]
@henrikbossart 
Okay, nice, thanks for the Typography tip. 
I'll fix the tests, and push the newest changes for you to review after.

**Review by henrikbossart — APPROVED** [review]

**Pull request merged**
